### ISSUE TITLE
Missing O_TMPFILE on some systems

### ISSUE THREAD

**Issue by mrc0mmand** [martinpitt/umockdev#84]
Hello!

I'm trying to build umockdev for RHEL/CentOS 7 to be able to use it in our systemd test suite, but I came across one issue. On CentOS/RHEL 7.5 and lower the `O_TMPFILE` constant is not defined, which causes a compilation error. Nevertheless, the `fnctl.h` header contains the `__O_TMPFILE` constant, so by applying a simple patch[0] I'm able to successfully build umockdev on CentOS 7[1].

I'm not sure if this is the ideal or even a safe solution. If so, I'll gladly open a PR, if not I'd definitely appreciate some advice.

Thanks!

[0] https://github.com/mrc0mmand/umockdev/commit/601a30e818b9784f87691c4a358363b710d00882
[1] https://copr.fedorainfracloud.org/coprs/mrc0mmand/umockdev/packages/

**Comment by martinpitt** [comment]
Thanks @mrc0mmand ! This looks fine aside from one issue which I commented on that commit. Please do open a PR, then we can see what CI has to say about it.

I see the [tests are happy](https://copr-be.cloud.fedoraproject.org/results/mrc0mmand/umockdev/epel-7-x86_64/00801278-umockdev/build.log.gz) on CentOS 7, so that's good.

If you want to go the extra mile, I [recently added docker based CI for Alpine](https://github.com/martinpitt/umockdev/commit/66f8cdac6b77eff89a24ba981de39a3e693740b6). I figure this should extend to testing on CentOS in a rather straightforward way, so if you are interested we can work on setting this up.

**Comment by mrc0mmand** [comment]
Thanks for the review, I opened a PR with the requested changes - Travis seems to like it. The Alpine CI is a great idea, I'll definitely look into that!
